import {
  BarChart3,
  Bell,
  MessageSquareText,
  ShieldUser,
  UserPlus,
  Users,
} from "lucide-react";
import type {
  SuperAdminActivity,
  SuperAdminMetric,
  SuperAdminNavItem,
  SuperAdminTableRow,
} from "@/types/super-admin";

export const SUPER_ADMIN_NAV_ITEMS: SuperAdminNavItem[] = [
  { key: "dashboard", label: "Dashboard", href: "/super-admin/dashboard" },
  { key: "admins", label: "Admins", href: "/super-admin/admins" },
  { key: "users", label: "Users", href: "/super-admin/users" },
  {
    key: "installers",
    label: "Installers",
    href: "/super-admin/installers",
  },
  { key: "onboarding-leads", label: "Leads", href: "/super-admin/onboarding-leads" },
  { key: "feedback", label: "Feedback", href: "/super-admin/feedback" },
  {
    key: "communications",
    label: "Communications",
    href: "/super-admin/communications",
  },
];

export const SUPER_ADMIN_METRICS: SuperAdminMetric[] = [
  {
    label: "New Users",
    value: "268",
    helper: "Smart inverter users this month",
    change: "+9.0% vs last month",
    icon: Users,
  },
  {
    label: "Total Users",
    value: "2,759",
    helper: "Households and businesses tracked",
    change: "+11.43% vs last month",
    icon: Users,
  },
  {
    label: "Active Installers",
    value: "128",
    helper: "Installer and EPC partner accounts",
    change: "+8.2% vs last month",
    icon: ShieldUser,
  },
  {
    label: "Open Feedback",
    value: "36",
    helper: "Product and pilot feedback items",
    change: "12 high priority",
    icon: MessageSquareText,
  },
];

export const SUPER_ADMIN_DASHBOARD_ROWS: SuperAdminTableRow[] = [
  {
    id: "USR-1029",
    name: "Auzan Nugraha Agustian",
    email: "auzan@example.com",
    status: "Active",
    role: "Free",
    date: "12 Aug 2026",
    meta: "Last active: today 10:04",
    amount: "$0.003",
    creditsUsed: "6,680",
    invitedMembers: "2 family members",
    invitedTechnicians: "1 technician",
    connectedInverters: "1 inverter",
    state: "Lagos",
    inverterType: "Deye hybrid inverter",
  },
  {
    id: "USR-1030",
    name: "Abdallah",
    email: "abdallah@example.com",
    status: "Active",
    role: "Installer referral",
    date: "12 Aug 2026",
    meta: "Last active: today 04:48",
    amount: "$0.011",
    creditsUsed: "19,283",
    invitedMembers: "3 team members",
    invitedTechnicians: "2 technicians",
    connectedInverters: "3 inverters",
    state: "Ogun",
    inverterType: "Must PV inverter",
  },
  {
    id: "USR-1031",
    name: "Mishi Chaudhary",
    email: "mishi@example.com",
    status: "Pending",
    role: "Pilot",
    date: "12 Aug 2026",
    meta: "Last active: today 00:07",
    amount: "$0.005",
    creditsUsed: "11,767",
    invitedMembers: "1 member",
    invitedTechnicians: "1 technician",
    connectedInverters: "2 inverters",
    state: "Abuja",
    inverterType: "LuxPower hybrid inverter",
  },
];

export const SUPER_ADMIN_ADMIN_ROWS: SuperAdminTableRow[] = [
  {
    id: "ADM-001",
    name: "Richard",
    email: "richard@intell.africa",
    status: "Active",
    role: "Admin",
    date: "May 8, 2026",
    meta: "Last Active: Jun 3, 06:47 PM",
  },
  {
    id: "ADM-002",
    name: "Sarah",
    email: "sarah@intell.africa",
    status: "Active",
    role: "Super Admin",
    date: "Mar 31, 2026",
    meta: "Last Active: Jul 6, 06:05 PM",
  },
  {
    id: "ADM-003",
    name: "John",
    email: "john@intell.africa",
    status: "Active",
    role: "Super Admin",
    date: "May 25, 2026",
    meta: "Last Active: Jul 30, 04:18 PM",
  },
];

export const SUPER_ADMIN_ACTIVITY_LOG: SuperAdminActivity[] = [
  {
    id: "ACT-001",
    action: "Super Admin promoted John to super admin",
    date: "25 May 2026, 10:25",
  },
  {
    id: "ACT-002",
    action: "Admin assigned pilot feedback review to product team",
    date: "24 May 2026, 16:00",
  },
  {
    id: "ACT-003",
    action: "Super Admin added installer onboarding checklist",
    date: "24 May 2026, 15:59",
  },
];

export const SUPER_ADMIN_USER_ROWS: SuperAdminTableRow[] = [
  {
    id: "USR-2201",
    name: "Daphne Luna",
    email: "daphne@example.com",
    status: "Active",
    role: "Free",
    date: "29 Jan 2026 at 15:16",
    meta: "Smart inverter user",
    amount: "$0",
    phone: "+234 810 111 2045",
    state: "Lagos",
    inverterType: "Deye hybrid inverter",
    creditsUsed: "0",
    invitedMembers: "2 members",
    invitedTechnicians: "1 technician",
    connectedInverters: "1 inverter",
  },
  {
    id: "USR-2202",
    name: "Manga Anime",
    email: "manga@example.com",
    status: "Active",
    role: "Free",
    date: "26 Jun 2026 at 21:45",
    meta: "Beta tester",
    amount: "$0.003",
    phone: "+234 810 212 3467",
    state: "Rivers",
    inverterType: "Growatt inverter",
    creditsUsed: "5,613",
    invitedMembers: "1 member",
    invitedTechnicians: "1 technician",
    connectedInverters: "1 inverter",
  },
  {
    id: "USR-2203",
    name: "2434 AYATA",
    email: "ayata@example.com",
    status: "Active",
    role: "Pilot",
    date: "24 Apr 2026 at 13:11",
    meta: "Installer-managed account",
    amount: "$0.003",
    phone: "+234 810 312 7800",
    state: "Oyo",
    inverterType: "Victron system",
    creditsUsed: "5,924",
    invitedMembers: "4 members",
    invitedTechnicians: "2 technicians",
    connectedInverters: "2 inverters",
  },
];

export const SUPER_ADMIN_INSTALLER_ROWS: SuperAdminTableRow[] = [
  {
    id: "INS-1101",
    name: "SolarBridge Energy",
    email: "ops@solarbridge.example",
    phone: "+234 810 771 4401",
    company: "SolarBridge Energy",
    state: "Lagos",
    sites: "18 managed sites",
    inverterType: "Deye, LuxPower, Victron",
    content: "Partner installer supporting residential and SME deployments.",
    installerType: "Partner",
    usersManaged: "42 users",
    region: "Lagos and Ogun",
    status: "Active",
    role: "Company Installer",
    date: "12 Aug 2026",
    meta: "Last active: today 09:20",
  },
  {
    id: "INS-1102",
    name: "Ifeanyi Okoro",
    email: "ifeanyi.installer@example.com",
    phone: "+234 810 551 0987",
    company: "Freelance",
    state: "Enugu",
    sites: "6 managed sites",
    inverterType: "Must PV, Growatt",
    content: "Freelance installer qualifying inverter compatibility in the east.",
    installerType: "Technician",
    usersManaged: "6 users",
    region: "South East",
    status: "Active",
    role: "Technician",
    date: "9 Aug 2026",
    meta: "Last active: Aug 10, 02:10 PM",
  },
  {
    id: "INS-1103",
    name: "NorthGrid Solar",
    email: "partners@northgrid.example",
    phone: "+234 810 321 1120",
    company: "NorthGrid Solar",
    state: "Kano",
    sites: "11 managed sites",
    inverterType: "Sunsynk, Deye",
    content: "Installer lead for multi-site business energy monitoring.",
    installerType: "Partner",
    usersManaged: "19 users",
    region: "Northern Nigeria",
    status: "Pending",
    role: "Company Installer",
    date: "5 Aug 2026",
    meta: "Last active: Aug 7, 11:43 AM",
  },
];

export const SUPER_ADMIN_ONBOARDING_LEAD_ROWS: SuperAdminTableRow[] = [
  {
    id: "LEAD-7001",
    name: "Blessing Adeyemi",
    email: "blessing@example.com",
    phone: "+234 810 900 1188",
    state: "Lagos",
    inverterType: "Deye hybrid inverter",
    content: "Wants to track battery drain and know if solar savings are real.",
    status: "Open",
    role: "Homeowner",
    source: "Instagram launch post",
    date: "Today",
    meta: "Interested in AI alerts",
  },
  {
    id: "LEAD-7002",
    name: "Tunde Balogun",
    email: "tunde@example.com",
    phone: "+234 810 455 2199",
    state: "Ogun",
    inverterType: "LuxPower hybrid inverter",
    content: "Needs monitoring for three branch offices before fuel costs rise.",
    status: "Contacted",
    role: "Business owner",
    source: "LinkedIn campaign",
    date: "12 Aug 2026",
    meta: "Multi-site lead",
  },
  {
    id: "LEAD-7003",
    name: "Adaeze Nwosu",
    email: "adaeze@example.com",
    phone: "+234 810 678 3344",
    state: "Abuja",
    inverterType: "Must PV inverter",
    content: "Asked for installer help and a simple savings report.",
    status: "Qualified",
    role: "Residential user",
    source: "WhatsApp referral",
    date: "10 Aug 2026",
    meta: "Needs installer follow-up",
  },
];

export const SUPER_ADMIN_FEEDBACK_ROWS: SuperAdminTableRow[] = [
  {
    id: "FDB-3301",
    name: "Savings forecast clarity",
    email: "daphne@example.com",
    submittedBy: "Daphne Luna",
    category: "Cost and savings report",
    content: "Users want clearer explanations for cost and savings reports.",
    status: "Open",
    priority: "High",
    date: "10/07/2026",
  },
  {
    id: "FDB-3302",
    name: "Report sharing",
    email: "manga@example.com",
    submittedBy: "Manga Anime",
    category: "Reports",
    content: "Make public report links easier to understand before sharing.",
    status: "In Progress",
    priority: "Medium",
    date: "07/06/2026",
  },
  {
    id: "FDB-3303",
    name: "Installer onboarding",
    email: "ayata@example.com",
    submittedBy: "2434 AYATA",
    category: "Installer access",
    content: "Installers need a shorter guide for qualifying compatible inverters.",
    status: "Open",
    priority: "-",
    date: "24/04/2026",
  },
];

export const SUPER_ADMIN_COMMUNICATION_ROWS: SuperAdminTableRow[] = [
  {
    id: "COM-5501",
    name: "Installer onboarding kit",
    content: "Partner guide for qualifying smart inverter and WiFi/GPRS systems.",
    audience: "Installer partners",
    body: "We are opening INTELL onboarding to installer partners who can help households and SMEs connect compatible inverters, monitor performance, and reduce avoidable downtime.",
    actionLabel: "Review onboarding guide",
    actionUrl: "https://intell.ng/onboard",
    status: "Scheduled",
    priority: "High",
    date: "Aug 12, 2026",
  },
  {
    id: "COM-5502",
    name: "Private pilot update",
    content: "WhatsApp and email update for the first pilot users.",
    audience: "Pilot users",
    body: "Your INTELL dashboard now helps you understand inverter health, savings trends, alerts, and AI guidance from one place.",
    actionLabel: "Open dashboard",
    actionUrl: "https://intell.ng/dashboard",
    status: "Draft",
    priority: "Medium",
    date: "Aug 9, 2026",
  },
  {
    id: "COM-5503",
    name: "Launch positioning",
    content: "Message focused on visibility, uptime, and installer trust.",
    audience: "Launch audience",
    body: "INTELL helps solar and inverter users stop guessing. Connect your inverter, track system behavior, receive proactive alerts, and make better energy decisions.",
    actionLabel: "Onboard now",
    actionUrl: "https://intell.ng/onboard",
    status: "Delivered",
    priority: "Low",
    date: "Aug 5, 2026",
  },
];

export const SUPER_ADMIN_FILTER_OPTIONS = {
  status: [
    "All",
    "Active",
    "Pending",
    "Qualified",
    "Contacted",
  ],
  communicationStatus: ["All", "Draft", "Scheduled", "Delivered", "Failed"],
  priority: ["All", "Low", "Medium", "High"],
  date: ["All", "Last Month", "Last 3 Months", "Last 6 Months", "Last Year"],
  role: ["All", "Admin", "Super Admin", "Company Installer", "Technician"],
  plan: ["All", "Free", "Paid", "Pilot", "Installer referral"],
  interest: ["All", "Homeowner", "Business owner", "Residential user"],
  installerType: ["All", "Partner", "Technician"],
};

export const SUPER_ADMIN_OVERVIEW_CHARTS = [
  {
    title: "Free vs Paid Users",
    value: "354 free / 12 paid",
    icon: BarChart3,
    input: [12, 18, 28, 46, 80, 64, 52, 48, 36],
    output: [4, 6, 8, 12, 18, 16, 14, 18, 12],
  },
  {
    title: "AI Credit Consumption",
    value: "30,212,186",
    icon: Bell,
    input: [10, 28, 52, 48, 42, 38, 54, 82, 50],
    output: [6, 18, 36, 32, 28, 24, 34, 58, 30],
  },
  {
    title: "Installer Pipeline",
    value: "24 partner leads",
    icon: UserPlus,
    input: [8, 12, 18, 20, 26, 34, 30, 38, 44],
    output: [4, 8, 10, 12, 18, 22, 20, 24, 28],
  },
];
